% Diffuse shortwave and longwave radiation onto point
function[SWRdiff_Person,LWR_Person]=SWRDiffPerson(SWRout_t,LWRout_t,MeteoData,ViewFactorPoint)


SWRdiff_Person	=	ViewFactorPoint.F_pg*SWRout_t.SWRoutTotalGround + ViewFactorPoint.F_ps*MeteoData.SW_diff +...
					ViewFactorPoint.F_pt*SWRout_t.SWRoutTree + ViewFactorPoint.F_pw*SWRout_t.SWRoutWallSun + ...
					ViewFactorPoint.F_pw*SWRout_t.SWRoutWallShade;

LWR_Person		=	ViewFactorPoint.F_pg*LWRout_t.LWRoutTotalGround + ViewFactorPoint.F_ps*MeteoData.LWR +...
					ViewFactorPoint.F_pt*LWRout_t.LWRoutTree + ViewFactorPoint.F_pw*LWRout_t.LWRoutWallSun + ...
					ViewFactorPoint.F_pw*LWRout_t.LWRoutWallShade;

